name: Regression Automated Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    # 🌟 Forzamos Ubuntu 22.04 para evitar el bug de dependencias del sistema operativo
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Instala los 3 navegadores (Chromium, Firefox y WebKit) con sus dependencias en una versión de OS compatible
    - name: Install Playwright Browsers & Deps
      run: python -m playwright install --with-deps

    # Corre tus tests pasando los 3 navegadores en paralelo
    - name: Run Pytest Tests
      env:
        BASE_URL: https://the-internet.herokuapp.com
      run: pytest --browser chromium --browser firefox --browser webkit